# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'your-container-image-name:$(build.buildId)'

steps:
- task: Docker@1
  displayName: 'Build an Image'
  inputs:
    imageName: 'joemctestacr.azurecr.io/aitest:$(Build.BuildId)'
- task: Docker@1
  displayName: 'Login to ACR'
  inputs:
    azureSubscriptionEndpoint: 'joemcacrtestconnection'
    azureContainerRegistry: joemctestacr.azurecr.io
    command: login
- task: Docker@1
  displayName: 'Push Image to ACR'
  inputs:
    command: 'push'
    imageName: 'joemctestacr.azurecr.io/aitest:$(Build.BuildId)'